### ISSUE TITLE
access of n rows grows as O(n^2)

### ISSUE THREAD

**Issue by lwaldron** [Huber-group-EMBL/rhdf5#31]
Here's a gist demonstrating O(n^2) growth of elapsed time to select n rows, sequentially or randomly, from a TCGA methylation dataset on ExperimentHub. I've posted some discussion on #bigdata-rep on the Bioc-community Slack channel but thought I should post it here in case the benchmarking is useful.

https://gist.github.com/lwaldron/44c7142adb04de03255cc37b0264acf6

![rplot](https://user-images.githubusercontent.com/639942/51107977-e995a880-17f0-11e9-923f-64bc46525fa1.png)

```
> class(dm)
[1] "DelayedMatrix"
attr(,"package")
[1] "DelayedArray"
> dim(dm)
[1] 27578   118
> chunkdim(dm)
[1] 15287    65
> r2  #r-squared, row number = polynomial degree
  sequential    random    firstn
1  0.8856380 0.9498821 0.3288355
2  0.9984106 0.9666444 0.3266328
3  0.9779928 0.8764857 0.3198614
4  0.9292532 0.7857453 0.3046170
```

**Comment by grimbough** [comment]
Hi Levi,

Thanks for the report.  I think this is related to the issues I'm addressing in Section 2 of https://www.bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/practical_tips.html which is primarily restricted by inefficiencies in HDF5 itself.  I'll check through the benchmark and make sure this is the same problem & not something else.

**Comment by grimbough** [comment]
Thanks for the code, it's been very helpful.  I've spent some time experimenting with how columns/rows are extracted in **rhdf5**.  It's a little hard to test using your example directly as **HDF5Array** is using it's own reading function at the moment and bypassing **rhdf5**.  However if I use the version of `h5read()` in **rhdf5** 2.27.5 directly I get very similar results to you:

![rhdf5_2 27 5](https://user-images.githubusercontent.com/971237/51346726-a4969e00-1a9e-11e9-84fd-0089779a913e.png)

Using the changes I've currently implemented this changes to:

![rhdf5_2 27 5-1](https://user-images.githubusercontent.com/971237/51346768-b415e700-1a9e-11e9-9369-d64c3f32ebab.png)

It's now a little slower for the random selection, and but quite a bit better for a more structured set of rows (I'm not sure why there's such an improvement at 10,000 rows but it seems consistent across several runs on my machine).

Currently the improvements only work in the case where we're selecting from a single dimension, and asking for all data in the other dimensions.  Selecting even a single column will return to the old performance.  Since this looks like a promising avenue I'll keep exploring.

**Comment by lwaldron** [comment]
Cool, glad I could contribute something useful to such a great package!

**Comment by grimbough** [comment]
I've made some more improvements in how **rhdf5** translates the index argument for selecting columns & rows in the the HDF5 hyperslab nomenclature.  It now tries to find underlying sequences in the given indices, to reduce the number of hyperslabs that need to be combined.

It's now pretty good for sequential sets of columns, and has pretty similar performance to before for random sets.  A comparison between the version currently in BioC and my changes is below:

![file_show](https://user-images.githubusercontent.com/971237/51549203-3d943300-1e6a-11e9-9207-b39b76320410.png)

Full benchmark code at:

https://gist.github.com/grimbough/e7477d1b40a61a6f012e0fda2299fc42

There's a few more tests to run to confirm I haven't broken anything and then I'll get it into BioC devel ASAP.

**Comment by vjcitn** [comment]
I just noticed these remarks on translation of the index argument.  We have code that does
this in rhdf5client -- it examines a run-length encoding of the request.  Can you point out the translation code in rhdf5?  It would be nice to compare.  I have long wondered if there is similar code in R itself to optimize fetching with complicated index expressions.

**Comment by grimbough** [comment]
Sounds like a very similar approach.  The relevant function is at https://github.com/grimbough/rhdf5/blob/ad317f2daac85b0929d42564606dea001b70f1e7/R/H5S.R#L239

It also uses a run length encoding to see if there are any patterns we can exploit to reduce the number of hyperslab unions.  I feel like there's probably a really neat mathematical solution, but for now I examine RLEs on differences with lags between 1 and 10, and then pick based on the fewest number of runs.  Changing the lag resolved the oddity in https://github.com/grimbough/rhdf5/issues/31#issuecomment-455323074 where picking 8000 rows was less efficient that picking 10,000.
