### ISSUE TITLE
rhdf5 on CRAN

### ISSUE THREAD

**Issue by JVAQUEROM** [Huber-group-EMBL/rhdf5#70]
Hi there!

I am big fan of rhdf5. However, I do not belong to the filed of bioinformatics. I wonder if this package could be on CRAN, along with other packages for georeferenced data, like `ncdf4`, `raster`, etc. I install `bioconductor` only to install this package. 

Just a suggestion.

Thank you and keep up the good work!

**Comment by grimbough** [comment]
Hi,

Thanks for your interest and support for rhdf5, I'm glad you find the package useful.  I agree that it's a more general purpose tool than most things in Bioconductor, however it's been in Bioconductor for 16 years now and I don't think I'm going to change that.  I also really value the 6-monthly release cycle that Bioconductor utilises, rather than constant rolling updates of CRAN packages.

Compared to if it was on CRAN, it should be sufficient to install only one extra package (**BiocManager**) to use rhdf5,  although I agree it's slightly confusing to have two different functions for installing packages e.g.

```r
install.packages('BiocManager')
BiocManager::install('rhdf5')
```

You should also be able to install directly from Github using the **remotes** package, and bypass any Bioconductor tools.  For example, the code below would install everything needed to run the Bioconductor 3.11 version of **rhdf5**.  *This probably won't work on Windows, as it requires compiling lots of C code, which is a definite disadvantage to this approach*.

```r
version = 'RELEASE_3_11'
remotes::install_github('grimbough/Rhdf5lib', ref = version)
remotes::install_github('grimbough/rhdf5filters', ref = version)
remotes::install_github('grimbough/rhdf5', ref = version)
```

Thanks again for the suggestion.

**Comment by JVAQUEROM** [comment]
Thank you for your information, I appreciate your answer.
