### ISSUE TITLE
rhdf5filters needs R 4.0

### ISSUE THREAD

**Issue by gouthamatla** [Huber-group-EMBL/rhdf5#74]
Hi I am trying to install `rhdf5` using Bioconductor version 3.10 and R 3.6.1 in a fresh conda environment. 

I am receiving the following error:

```
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib -Wl,-rpath-link,/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib -L/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib -L/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib -Wl,-rpath-link,/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib -o rhdf5.so H5.o H5A.o H5D.o H5E.o H5F.o H5G.o H5I.o H5L.o H5O.o H5P.o H5S.o H5T.o H5Z.o H5constants.o HandleList.o HandleListWrap.o h5dump.o h5ls.o h5testLock.o h5writeDataFrame.o printdatatype.o wrap.o Fatal error: creating temporary file for -e failed -L/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib/R/lib -lR
x86_64-conda_cos6-linux-gnu-c++: error: Fatal: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: error:: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: creating: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: temporary: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: file: No such file or directory
x86_64-conda_cos6-linux-gnu-c++: error: for: No such file or directory
make: *** [/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib/R/share/make/shlib.mk:6: rhdf5.so] Error 1
ERROR: compilation failed for package 'rhdf5'
* removing '/rds/general/user/gatla/home/anaconda3/envs/r361_cicero/lib/R/library/rhdf5'

The downloaded source packages are in
	'/rds/general/ephemeral/user/gatla/ephemeral/RtmpP7DfTS/downloaded_packages'
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(...) :
  installation of package 'rhdf5' had non-zero exit status

```

I am not sure why the error message is a part of the command and seems like some permission issues. 

So I tried to install manually using R CMD INSTALL. Seems like it depends on "rhdf5filters". 

When I try to install rhdf5filters, it says that it is not available for R 3.6.1

```
> BiocManager::install("rhdf5filters") 
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.1 (2019-07-05)
Installing package(s) 'rhdf5filters'
Warning message:
package 'rhdf5filters' is not available (for R version 3.6.1) 

```

**Comment by grimbough** [comment]
There's a few things going on here.  

First off, what commands did you run that lead to the first error you've posted?

Regarding **rhdf5filters**, formally there are no restrictions on the versions of R it will work with.  However because it's available from Bioconductor, which has a six monthly release cycle tied to specific R versions, there are some practical limitations that you might need to work around.  *rhdf5filters** was only introduced in Bioconductor 3.11, and so as far as your R 3.6 / BioC 3.10 setup is concerned, the package isn't available via the repositories.

You can try installing via Github with `BiocManager::install('grimbough/rhdf5filters')` however, I don't know how well this will work in Anaconda.  I have mixed experiences building packages from source when using R installed via conda.
